name: Format and Lint

on:
  push:

jobs:
  format_job:
    name: Format Job
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'

    - name: Install dependencies
      run: npm ci

    - name: Run Prettier formatting
      run: npm run format
