name: Style check CI

on:
  pull_request:
    branches:
      - master

jobs:
  prettier_job:
    name: Prettier

    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run format-check

  eslint_job:
    name: ESLint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  check_filesize_job:
    name: Check file size

    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get Changed Files from GitHub Actions Marketplace
        id: changed-files
        uses: tj-actions/changed-files@2f7c5bfce28377bc069a65ba478de0a74aa0ca32

      - name: Check file size
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [ -f "$file" ] && [ $(stat -f%z "$file" 2>/dev/null || stat -c%s "$file") -gt 307200 ]; then
              echo "File $file is larger than 300k"
              exit 1
            fi
          done

  astro_check_job:
    name: Astro Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Install dependencies
        run: npm ci

      - name: Run Astro Check
        run: npm run check
