name: Typecheck CI

on:
  pull_request:
    branches:
      - master

jobs:
  prettier_job:
    name: Prettier
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npx prettier --check "**/*.{js,jsx,ts,tsx,json,md,mdx,css,scss,yml,yaml}"

  eslint_job:
    name: ESLint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
